# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Fri Aug 21 10:42:10 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1465, 869)
        MainWindow.setCursor(QtCore.Qt.ArrowCursor)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("BOUTguilogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setToolTip("")
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Load = QtGui.QWidget()
        self.Load.setEnabled(True)
        self.Load.setObjectName("Load")
        self.pushButton = QtGui.QPushButton(self.Load)
        self.pushButton.setGeometry(QtCore.QRect(1320, 716, 81, 25))
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtGui.QTableWidget(self.Load)
        self.tableWidget.setGeometry(QtCore.QRect(20, 20, 1381, 691))
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.archivePath = QtGui.QLabel(self.Load)
        self.archivePath.setGeometry(QtCore.QRect(177, 718, 951, 20))
        self.archivePath.setObjectName("archivePath")
        self.label_18 = QtGui.QLabel(self.Load)
        self.label_18.setGeometry(QtCore.QRect(20, 720, 201, 16))
        self.label_18.setObjectName("label_18")
        self.tabWidget.addTab(self.Load, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.checkBox = QtGui.QCheckBox(self.tab_2)
        self.checkBox.setGeometry(QtCore.QRect(1171, 725, 71, 20))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_3 = QtGui.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(1250, 692, 161, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.procSpin = QtGui.QSpinBox(self.tab_2)
        self.procSpin.setGeometry(QtCore.QRect(1060, 693, 53, 22))
        self.procSpin.setObjectName("procSpin")
        self.niceSpin = QtGui.QSpinBox(self.tab_2)
        self.niceSpin.setGeometry(QtCore.QRect(1060, 723, 53, 22))
        self.niceSpin.setMinimum(-99)
        self.niceSpin.setObjectName("niceSpin")
        self.groupBox_18 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_18.setGeometry(QtCore.QRect(913, 617, 501, 71))
        self.groupBox_18.setObjectName("groupBox_18")
        self.plainTextEdit = QtGui.QPlainTextEdit(self.groupBox_18)
        self.plainTextEdit.setGeometry(QtCore.QRect(4, 14, 491, 51))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(959, 725, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(919, 695, 151, 16))
        self.label.setObjectName("label")
        self.pushButton_2 = QtGui.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(1170, 692, 75, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.runScanningSimulation = QtGui.QPushButton(self.tab_2)
        self.runScanningSimulation.setGeometry(QtCore.QRect(1250, 720, 161, 25))
        self.runScanningSimulation.setObjectName("runScanningSimulation")
        self.fileLabel = QtGui.QLabel(self.tab_2)
        self.fileLabel.setGeometry(QtCore.QRect(90, 723, 771, 16))
        self.fileLabel.setObjectName("fileLabel")
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(10, 723, 91, 16))
        self.label_15.setObjectName("label_15")
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(10, 708, 201, 16))
        self.label_17.setObjectName("label_17")
        self.simulationFile = QtGui.QLabel(self.tab_2)
        self.simulationFile.setGeometry(QtCore.QRect(200, 708, 771, 16))
        self.simulationFile.setObjectName("simulationFile")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.outputStream = QtGui.QTextBrowser(self.tab)
        self.outputStream.setGeometry(QtCore.QRect(10, 10, 1401, 691))
        self.outputStream.setObjectName("outputStream")
        self.stopSimulation = QtGui.QPushButton(self.tab)
        self.stopSimulation.setGeometry(QtCore.QRect(10, 710, 1401, 25))
        self.stopSimulation.setObjectName("stopSimulation")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textOutput = QtGui.QTextEdit(self.tab_3)
        self.textOutput.setGeometry(QtCore.QRect(22, 430, 661, 261))
        self.textOutput.setReadOnly(True)
        self.textOutput.setObjectName("textOutput")
        self.label_64 = QtGui.QLabel(self.tab_3)
        self.label_64.setGeometry(QtCore.QRect(20, 700, 64, 25))
        self.label_64.setObjectName("label_64")
        self.dataTable = QtGui.QTableWidget(self.tab_3)
        self.dataTable.setGeometry(QtCore.QRect(23, 210, 661, 221))
        self.dataTable.setAlternatingRowColors(True)
        self.dataTable.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.dataTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.dataTable.setShowGrid(False)
        self.dataTable.setGridStyle(QtCore.Qt.SolidLine)
        self.dataTable.setObjectName("dataTable")
        self.dataTable.setColumnCount(4)
        self.dataTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(3, item)
        self.dataTable.horizontalHeader().setStretchLastSection(True)
        self.dataTable.verticalHeader().setDefaultSectionSize(20)
        self.commandButton = QtGui.QPushButton(self.tab_3)
        self.commandButton.setGeometry(QtCore.QRect(610, 700, 75, 25))
        self.commandButton.setObjectName("commandButton")
        self.frame = QtGui.QFrame(self.tab_3)
        self.frame.setGeometry(QtCore.QRect(700, 104, 701, 621))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.commandInput = ConsoleWidget(self.tab_3)
        self.commandInput.setGeometry(QtCore.QRect(89, 702, 511, 21))
        self.commandInput.setObjectName("commandInput")
        self.groupBox = QtGui.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(23, 4, 661, 201))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_7 = QtGui.QPushButton(self.groupBox)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 30, 101, 25))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.collectedLabel_3 = QtGui.QLabel(self.groupBox)
        self.collectedLabel_3.setGeometry(QtCore.QRect(10, 89, 171, 16))
        self.collectedLabel_3.setObjectName("collectedLabel_3")
        self.extraVarsCombo = QtGui.QComboBox(self.groupBox)
        self.extraVarsCombo.setGeometry(QtCore.QRect(10, 109, 151, 22))
        self.extraVarsCombo.setObjectName("extraVarsCombo")
        self.collectExtraVariable = QtGui.QPushButton(self.groupBox)
        self.collectExtraVariable.setGeometry(QtCore.QRect(170, 109, 101, 25))
        self.collectExtraVariable.setObjectName("collectExtraVariable")
        self.collectedLabel = QtGui.QLabel(self.groupBox)
        self.collectedLabel.setGeometry(QtCore.QRect(100, 160, 760, 16))
        self.collectedLabel.setObjectName("collectedLabel")
        self.label_22 = QtGui.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(10, 160, 150, 16))
        self.label_22.setObjectName("label_22")
        self.groupBox_2 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(700, 4, 701, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.collectedLabel_2 = QtGui.QLabel(self.groupBox_2)
        self.collectedLabel_2.setGeometry(QtCore.QRect(10, 15, 181, 16))
        self.collectedLabel_2.setObjectName("collectedLabel_2")
        self.saveDefaultButton = QtGui.QPushButton(self.groupBox_2)
        self.saveDefaultButton.setGeometry(QtCore.QRect(10, 60, 81, 25))
        self.saveDefaultButton.setObjectName("saveDefaultButton")
        self.defaultCombo = QtGui.QComboBox(self.groupBox_2)
        self.defaultCombo.setGeometry(QtCore.QRect(10, 35, 171, 22))
        self.defaultCombo.setObjectName("defaultCombo")
        self.defaultCombo.addItem("")
        self.zall = QtGui.QCheckBox(self.groupBox_2)
        self.zall.setGeometry(QtCore.QRect(500, 65, 41, 20))
        self.zall.setObjectName("zall")
        self.yall = QtGui.QCheckBox(self.groupBox_2)
        self.yall.setGeometry(QtCore.QRect(440, 65, 41, 20))
        self.yall.setObjectName("yall")
        self.xall = QtGui.QCheckBox(self.groupBox_2)
        self.xall.setGeometry(QtCore.QRect(380, 65, 41, 20))
        self.xall.setObjectName("xall")
        self.deleteButton = QtGui.QPushButton(self.groupBox_2)
        self.deleteButton.setGeometry(QtCore.QRect(100, 60, 81, 25))
        self.deleteButton.setObjectName("deleteButton")
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(230, 14, 301, 16))
        self.label_16.setObjectName("label_16")
        self.variableCombo = QtGui.QComboBox(self.groupBox_2)
        self.variableCombo.setGeometry(QtCore.QRect(230, 35, 81, 22))
        self.variableCombo.setObjectName("variableCombo")
        self.tall = QtGui.QCheckBox(self.groupBox_2)
        self.tall.setGeometry(QtCore.QRect(320, 65, 41, 20))
        self.tall.setObjectName("tall")
        self.xspin = QtGui.QSpinBox(self.groupBox_2)
        self.xspin.setGeometry(QtCore.QRect(380, 35, 53, 22))
        self.xspin.setMinimum(-10000000)
        self.xspin.setMaximum(10000000)
        self.xspin.setObjectName("xspin")
        self.zspin = QtGui.QSpinBox(self.groupBox_2)
        self.zspin.setGeometry(QtCore.QRect(500, 35, 53, 22))
        self.zspin.setMinimum(-1000000)
        self.zspin.setMaximum(10000000)
        self.zspin.setObjectName("zspin")
        self.yspin = QtGui.QSpinBox(self.groupBox_2)
        self.yspin.setGeometry(QtCore.QRect(440, 35, 53, 22))
        self.yspin.setMinimum(-999900)
        self.yspin.setMaximum(100000000)
        self.yspin.setObjectName("yspin")
        self.tspin = QtGui.QSpinBox(self.groupBox_2)
        self.tspin.setGeometry(QtCore.QRect(320, 35, 53, 22))
        self.tspin.setMinimum(-10000000)
        self.tspin.setMaximum(10000000)
        self.tspin.setProperty("value", 0)
        self.tspin.setObjectName("tspin")
        self.createGraph = QtGui.QPushButton(self.groupBox_2)
        self.createGraph.setGeometry(QtCore.QRect(590, 34, 101, 25))
        self.createGraph.setObjectName("createGraph")
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1465, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCompare = QtGui.QAction(MainWindow)
        self.actionCompare.setObjectName("actionCompare")
        self.actionFileHistory = QtGui.QAction(MainWindow)
        self.actionFileHistory.setObjectName("actionFileHistory")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionStop_Simulation = QtGui.QAction(MainWindow)
        self.actionStop_Simulation.setObjectName("actionStop_Simulation")
        self.actionPositioning = QtGui.QAction(MainWindow)
        self.actionPositioning.setObjectName("actionPositioning")
        self.actionArchive = QtGui.QAction(MainWindow)
        self.actionArchive.setObjectName("actionArchive")
        self.actionCreate_Example = QtGui.QAction(MainWindow)
        self.actionCreate_Example.setObjectName("actionCreate_Example")
        self.actionSimulation_Code = QtGui.QAction(MainWindow)
        self.actionSimulation_Code.setObjectName("actionSimulation_Code")
        self.actionDefault_Variables = QtGui.QAction(MainWindow)
        self.actionDefault_Variables.setObjectName("actionDefault_Variables")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionArchive)
        self.menuFile.addAction(self.actionSimulation_Code)
        self.menuFile.addAction(self.actionDefault_Variables)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionFileHistory)
        self.menuFile.addAction(self.actionCompare)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionStop_Simulation)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionHelp)
        self.menuView.addAction(self.actionPositioning)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "BOUTgui", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Loads the selected file for simualtion after editing", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "File Path", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Date Created", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Date Modified", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "No of Processors", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.archivePath.setToolTip(QtGui.QApplication.translate("MainWindow", "Shows the file path of the current archive", None, QtGui.QApplication.UnicodeUTF8))
        self.archivePath.setText(QtGui.QApplication.translate("MainWindow", "None loaded or bad file path, click File -> Archive Location to load", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Current Archive Folder =", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Load), QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setToolTip(QtGui.QApplication.translate("MainWindow", "If checked runs the simulations from the previous data", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainWindow", "Restart", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setToolTip(QtGui.QApplication.translate("MainWindow", "Run the simulation with all the user settings ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Run Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.procSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Change the number of processor to run the simulation on", None, QtGui.QApplication.UnicodeUTF8))
        self.niceSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Set the niceness level of the simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_18.setTitle(QtGui.QApplication.translate("MainWindow", "Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.plainTextEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "Type comments in here that will be saved in the archive", None, QtGui.QApplication.UnicodeUTF8))
        self.plainTextEdit.setPlainText(QtGui.QApplication.translate("MainWindow", "Write any useful comments here...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setToolTip(QtGui.QApplication.translate("MainWindow", "Set the niceness level of the simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "\'Niceness\' level:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setToolTip(QtGui.QApplication.translate("MainWindow", "Change the number of processor to run the simulation on", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Number of Processors:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setToolTip(QtGui.QApplication.translate("MainWindow", "Save changes made to the control file without running anything", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Write to file", None, QtGui.QApplication.UnicodeUTF8))
        self.runScanningSimulation.setToolTip(QtGui.QApplication.translate("MainWindow", "Runs a series of simulations given an increment, a starting variable and a final variable", None, QtGui.QApplication.UnicodeUTF8))
        self.runScanningSimulation.setText(QtGui.QApplication.translate("MainWindow", "Run Scanning Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.fileLabel.setToolTip(QtGui.QApplication.translate("MainWindow", "Current config filepath", None, QtGui.QApplication.UnicodeUTF8))
        self.fileLabel.setText(QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Open File =", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Current Simulation Code File = ", None, QtGui.QApplication.UnicodeUTF8))
        self.simulationFile.setToolTip(QtGui.QApplication.translate("MainWindow", "File path of the simulation code that will be used in the simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.simulationFile.setText(QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Change Inputs", None, QtGui.QApplication.UnicodeUTF8))
        self.outputStream.setToolTip(QtGui.QApplication.translate("MainWindow", "The output stream, showing simualtion data from the BOUT code", None, QtGui.QApplication.UnicodeUTF8))
        self.stopSimulation.setToolTip(QtGui.QApplication.translate("MainWindow", "Stop the simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.stopSimulation.setText(QtGui.QApplication.translate("MainWindow", "Stop Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Output Stream", None, QtGui.QApplication.UnicodeUTF8))
        self.textOutput.setToolTip(QtGui.QApplication.translate("MainWindow", "The printed output from commands", None, QtGui.QApplication.UnicodeUTF8))
        self.label_64.setText(QtGui.QApplication.translate("MainWindow", "Command:", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTable.setToolTip(QtGui.QApplication.translate("MainWindow", "Table showing the current variables and imported modules", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Trace", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.commandButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Run current command", None, QtGui.QApplication.UnicodeUTF8))
        self.commandButton.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.frame.setToolTip(QtGui.QApplication.translate("MainWindow", "Graphing area, any plots appear here", None, QtGui.QApplication.UnicodeUTF8))
        self.commandInput.setToolTip(QtGui.QApplication.translate("MainWindow", "Enter commands as if into a python command line", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Collection of Variables", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setToolTip(QtGui.QApplication.translate("MainWindow", "Imports the data from the current folder to be used for analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("MainWindow", "Collect Data", None, QtGui.QApplication.UnicodeUTF8))
        self.collectedLabel_3.setText(QtGui.QApplication.translate("MainWindow", "Additional Collect Variables :", None, QtGui.QApplication.UnicodeUTF8))
        self.extraVarsCombo.setToolTip(QtGui.QApplication.translate("MainWindow", "choose a non-default variable to collect", None, QtGui.QApplication.UnicodeUTF8))
        self.collectExtraVariable.setToolTip(QtGui.QApplication.translate("MainWindow", "Import data from a non-default variable (add defaults file -> default variables)", None, QtGui.QApplication.UnicodeUTF8))
        self.collectExtraVariable.setText(QtGui.QApplication.translate("MainWindow", "Collect Variable", None, QtGui.QApplication.UnicodeUTF8))
        self.collectedLabel.setToolTip(QtGui.QApplication.translate("MainWindow", "The folder path showing the location of the data files", None, QtGui.QApplication.UnicodeUTF8))
        self.collectedLabel.setText(QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setToolTip(QtGui.QApplication.translate("MainWindow", "The current source of data in use", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Collect From :", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Plotting", None, QtGui.QApplication.UnicodeUTF8))
        self.collectedLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Load a default input selection", None, QtGui.QApplication.UnicodeUTF8))
        self.saveDefaultButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Save current settings so they can be used again", None, QtGui.QApplication.UnicodeUTF8))
        self.saveDefaultButton.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultCombo.setToolTip(QtGui.QApplication.translate("MainWindow", "Select default settings", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultCombo.setItemText(0, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.zall.setToolTip(QtGui.QApplication.translate("MainWindow", "Select all of z", None, QtGui.QApplication.UnicodeUTF8))
        self.zall.setText(QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.yall.setToolTip(QtGui.QApplication.translate("MainWindow", "Select all of y", None, QtGui.QApplication.UnicodeUTF8))
        self.yall.setText(QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.xall.setToolTip(QtGui.QApplication.translate("MainWindow", "Select all of x ", None, QtGui.QApplication.UnicodeUTF8))
        self.xall.setText(QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Save current settings so they can be used again", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Input of form: variable(t,x,y,z) :", None, QtGui.QApplication.UnicodeUTF8))
        self.variableCombo.setToolTip(QtGui.QApplication.translate("MainWindow", "Choose what variable to plot", None, QtGui.QApplication.UnicodeUTF8))
        self.tall.setToolTip(QtGui.QApplication.translate("MainWindow", "Select all of time ", None, QtGui.QApplication.UnicodeUTF8))
        self.tall.setText(QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.xspin.setToolTip(QtGui.QApplication.translate("MainWindow", "x value", None, QtGui.QApplication.UnicodeUTF8))
        self.zspin.setToolTip(QtGui.QApplication.translate("MainWindow", "z value", None, QtGui.QApplication.UnicodeUTF8))
        self.yspin.setToolTip(QtGui.QApplication.translate("MainWindow", "y value", None, QtGui.QApplication.UnicodeUTF8))
        self.tspin.setToolTip(QtGui.QApplication.translate("MainWindow", "Time value", None, QtGui.QApplication.UnicodeUTF8))
        self.createGraph.setToolTip(QtGui.QApplication.translate("MainWindow", "Display the data selected as a graph", None, QtGui.QApplication.UnicodeUTF8))
        self.createGraph.setText(QtGui.QApplication.translate("MainWindow", "Create Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Graphing", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompare.setText(QtGui.QApplication.translate("MainWindow", "Compare", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompare.setToolTip(QtGui.QApplication.translate("MainWindow", "Once a file has been initially loaded this can be selected to compare differences between a second file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompare.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Alt+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileHistory.setText(QtGui.QApplication.translate("MainWindow", "File History", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileHistory.setToolTip(QtGui.QApplication.translate("MainWindow", "Brings up the automatically created history file which details the files family tree", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileHistory.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+H", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setShortcut(QtGui.QApplication.translate("MainWindow", "F11", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop_Simulation.setText(QtGui.QApplication.translate("MainWindow", "Stop Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop_Simulation.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPositioning.setText(QtGui.QApplication.translate("MainWindow", "Edit Input Positioning", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPositioning.setToolTip(QtGui.QApplication.translate("MainWindow", "Change the positioning of the input boxes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPositioning.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+B", None, QtGui.QApplication.UnicodeUTF8))
        self.actionArchive.setText(QtGui.QApplication.translate("MainWindow", "Archive Location", None, QtGui.QApplication.UnicodeUTF8))
        self.actionArchive.setToolTip(QtGui.QApplication.translate("MainWindow", "This allows the selection of folder to use as an archive", None, QtGui.QApplication.UnicodeUTF8))
        self.actionArchive.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreate_Example.setText(QtGui.QApplication.translate("MainWindow", "Create Example", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreate_Example.setToolTip(QtGui.QApplication.translate("MainWindow", "This creates an example folder in the selected archive", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimulation_Code.setText(QtGui.QApplication.translate("MainWindow", "Simulation Code", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimulation_Code.setToolTip(QtGui.QApplication.translate("MainWindow", "This allows the code used for simulations to be changed, so different models can be used", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSimulation_Code.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDefault_Variables.setText(QtGui.QApplication.translate("MainWindow", "Default Variables", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDefault_Variables.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

from console_widget import ConsoleWidget
