# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Jul 22 09:13:17 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1436, 828)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setToolTip("")
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Load = QtGui.QWidget()
        self.Load.setEnabled(True)
        self.Load.setObjectName("Load")
        self.pushButton = QtGui.QPushButton(self.Load)
        self.pushButton.setGeometry(QtCore.QRect(10, 690, 1421, 25))
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtGui.QTableWidget(self.Load)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 1421, 671))
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.tabWidget.addTab(self.Load, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_2 = QtGui.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(1170, 670, 75, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtGui.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(1250, 670, 161, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.checkBox = QtGui.QCheckBox(self.tab_2)
        self.checkBox.setGeometry(QtCore.QRect(1030, 670, 131, 20))
        self.checkBox.setObjectName("checkBox")
        self.fileLabel = QtGui.QLabel(self.tab_2)
        self.fileLabel.setGeometry(QtCore.QRect(90, 680, 771, 16))
        self.fileLabel.setObjectName("fileLabel")
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(10, 680, 91, 16))
        self.label_15.setObjectName("label_15")
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 200, 221, 371))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget = QtGui.QWidget(self.groupBox_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 201, 351))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.nxSpin = QtGui.QSpinBox(self.formLayoutWidget)
        self.nxSpin.setProperty("value", 1)
        self.nxSpin.setObjectName("nxSpin")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.nxSpin)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.nySpin = QtGui.QSpinBox(self.formLayoutWidget)
        self.nySpin.setMaximum(100000)
        self.nySpin.setSingleStep(1)
        self.nySpin.setProperty("value", 200)
        self.nySpin.setObjectName("nySpin")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.nySpin)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lengthSpin = QtGui.QSpinBox(self.formLayoutWidget)
        self.lengthSpin.setMaximum(1000)
        self.lengthSpin.setProperty("value", 100)
        self.lengthSpin.setObjectName("lengthSpin")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lengthSpin)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.dxSpin = QtGui.QSpinBox(self.formLayoutWidget)
        self.dxSpin.setProperty("value", 1)
        self.dxSpin.setObjectName("dxSpin")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.dxSpin)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.dyLine = QtGui.QLineEdit(self.formLayoutWidget)
        self.dyLine.setObjectName("dyLine")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.dyLine)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.ixseps1Spin = QtGui.QSpinBox(self.formLayoutWidget)
        self.ixseps1Spin.setMinimum(-50)
        self.ixseps1Spin.setMaximum(50)
        self.ixseps1Spin.setProperty("value", -1)
        self.ixseps1Spin.setObjectName("ixseps1Spin")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.ixseps1Spin)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.ixseps2Spin = QtGui.QSpinBox(self.formLayoutWidget)
        self.ixseps2Spin.setMinimum(-50)
        self.ixseps2Spin.setMaximum(50)
        self.ixseps2Spin.setProperty("value", -1)
        self.ixseps2Spin.setObjectName("ixseps2Spin")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.ixseps2Spin)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.rxySpin = QtGui.QSpinBox(self.formLayoutWidget)
        self.rxySpin.setMinimum(-50)
        self.rxySpin.setProperty("value", 1)
        self.rxySpin.setObjectName("rxySpin")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.rxySpin)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_9)
        self.bpxySpin = QtGui.QSpinBox(self.formLayoutWidget)
        self.bpxySpin.setMinimum(-50)
        self.bpxySpin.setProperty("value", 1)
        self.bpxySpin.setObjectName("bpxySpin")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.bpxySpin)
        self.label_10 = QtGui.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_10)
        self.btxySpin = QtGui.QSpinBox(self.formLayoutWidget)
        self.btxySpin.setMinimum(-50)
        self.btxySpin.setObjectName("btxySpin")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.btxySpin)
        self.label_11 = QtGui.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_11)
        self.bxySpin = QtGui.QSpinBox(self.formLayoutWidget)
        self.bxySpin.setMinimum(-50)
        self.bxySpin.setProperty("value", 1)
        self.bxySpin.setObjectName("bxySpin")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.bxySpin)
        self.label_12 = QtGui.QLabel(self.formLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_12)
        self.htheSpin = QtGui.QSpinBox(self.formLayoutWidget)
        self.htheSpin.setMinimum(-50)
        self.htheSpin.setProperty("value", 1)
        self.htheSpin.setObjectName("htheSpin")
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.htheSpin)
        self.label_13 = QtGui.QLabel(self.formLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.label_13)
        self.sintySpin = QtGui.QSpinBox(self.formLayoutWidget)
        self.sintySpin.setMinimum(-50)
        self.sintySpin.setObjectName("sintySpin")
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.sintySpin)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(319, 20, 221, 511))
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayoutWidget_5 = QtGui.QWidget(self.groupBox_3)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(7, 16, 201, 494))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_6 = QtGui.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_28 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_28.setObjectName("label_28")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_28)
        self.diagnoseCombo = QtGui.QComboBox(self.formLayoutWidget_5)
        self.diagnoseCombo.setObjectName("diagnoseCombo")
        self.diagnoseCombo.addItem("")
        self.diagnoseCombo.addItem("")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.diagnoseCombo)
        self.label_29 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_29.setObjectName("label_29")
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_29)
        self.label_30 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_30.setObjectName("label_30")
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_30)
        self.label_31 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_31.setObjectName("label_31")
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_31)
        self.label_32 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_32.setObjectName("label_32")
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_32)
        self.TnormSpin = QtGui.QSpinBox(self.formLayoutWidget_5)
        self.TnormSpin.setMinimum(-10000)
        self.TnormSpin.setMaximum(100000)
        self.TnormSpin.setProperty("value", 100)
        self.TnormSpin.setObjectName("TnormSpin")
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.TnormSpin)
        self.label_33 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_33.setObjectName("label_33")
        self.formLayout_6.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_33)
        self.label_34 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_34.setObjectName("label_34")
        self.formLayout_6.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_34)
        self.label_35 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_35.setObjectName("label_35")
        self.formLayout_6.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_35)
        self.label_36 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_36.setObjectName("label_36")
        self.formLayout_6.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_36)
        self.EionizeSpin = QtGui.QSpinBox(self.formLayoutWidget_5)
        self.EionizeSpin.setMinimum(-10000)
        self.EionizeSpin.setMaximum(10000)
        self.EionizeSpin.setProperty("value", 30)
        self.EionizeSpin.setObjectName("EionizeSpin")
        self.formLayout_6.setWidget(5, QtGui.QFormLayout.FieldRole, self.EionizeSpin)
        self.label_37 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_37.setObjectName("label_37")
        self.formLayout_6.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_37)
        self.label_38 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_38.setObjectName("label_38")
        self.formLayout_6.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_38)
        self.label_39 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_39.setObjectName("label_39")
        self.formLayout_6.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_39)
        self.label_40 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_40.setObjectName("label_40")
        self.formLayout_6.setWidget(12, QtGui.QFormLayout.LabelRole, self.label_40)
        self.label_41 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_41.setObjectName("label_41")
        self.formLayout_6.setWidget(13, QtGui.QFormLayout.LabelRole, self.label_41)
        self.label_42 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_42.setObjectName("label_42")
        self.formLayout_6.setWidget(15, QtGui.QFormLayout.LabelRole, self.label_42)
        self.label_43 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_43.setObjectName("label_43")
        self.formLayout_6.setWidget(16, QtGui.QFormLayout.LabelRole, self.label_43)
        self.atomicCombo = QtGui.QComboBox(self.formLayoutWidget_5)
        self.atomicCombo.setObjectName("atomicCombo")
        self.atomicCombo.addItem("")
        self.atomicCombo.addItem("")
        self.formLayout_6.setWidget(16, QtGui.QFormLayout.FieldRole, self.atomicCombo)
        self.label_44 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_44.setObjectName("label_44")
        self.formLayout_6.setWidget(17, QtGui.QFormLayout.LabelRole, self.label_44)
        self.label_45 = QtGui.QLabel(self.formLayoutWidget_5)
        self.label_45.setObjectName("label_45")
        self.formLayout_6.setWidget(18, QtGui.QFormLayout.LabelRole, self.label_45)
        self.gaspuffSpin = QtGui.QSpinBox(self.formLayoutWidget_5)
        self.gaspuffSpin.setMinimum(-100)
        self.gaspuffSpin.setObjectName("gaspuffSpin")
        self.formLayout_6.setWidget(10, QtGui.QFormLayout.FieldRole, self.gaspuffSpin)
        self.redist_weightLine = QtGui.QLineEdit(self.formLayoutWidget_5)
        self.redist_weightLine.setObjectName("redist_weightLine")
        self.formLayout_6.setWidget(9, QtGui.QFormLayout.FieldRole, self.redist_weightLine)
        self.hyperSpin = QtGui.QSpinBox(self.formLayoutWidget_5)
        self.hyperSpin.setStatusTip("")
        self.hyperSpin.setMinimum(-10000)
        self.hyperSpin.setMaximum(10000)
        self.hyperSpin.setProperty("value", 100)
        self.hyperSpin.setObjectName("hyperSpin")
        self.formLayout_6.setWidget(18, QtGui.QFormLayout.FieldRole, self.hyperSpin)
        self.areaLine = QtGui.QLineEdit(self.formLayoutWidget_5)
        self.areaLine.setStatusTip("")
        self.areaLine.setObjectName("areaLine")
        self.formLayout_6.setWidget(17, QtGui.QFormLayout.FieldRole, self.areaLine)
        self.BnormdoubleSpin = QtGui.QDoubleSpinBox(self.formLayoutWidget_5)
        self.BnormdoubleSpin.setMinimum(-10.0)
        self.BnormdoubleSpin.setSingleStep(0.1)
        self.BnormdoubleSpin.setProperty("value", 1.0)
        self.BnormdoubleSpin.setObjectName("BnormdoubleSpin")
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.FieldRole, self.BnormdoubleSpin)
        self.AAdoubleSpin = QtGui.QDoubleSpinBox(self.formLayoutWidget_5)
        self.AAdoubleSpin.setMinimum(-10.0)
        self.AAdoubleSpin.setSingleStep(0.1)
        self.AAdoubleSpin.setProperty("value", 1.0)
        self.AAdoubleSpin.setObjectName("AAdoubleSpin")
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.FieldRole, self.AAdoubleSpin)
        self.vwallSpin = QtGui.QDoubleSpinBox(self.formLayoutWidget_5)
        self.vwallSpin.setMinimum(-10.0)
        self.vwallSpin.setSingleStep(0.1)
        self.vwallSpin.setProperty("value", 1.0)
        self.vwallSpin.setObjectName("vwallSpin")
        self.formLayout_6.setWidget(6, QtGui.QFormLayout.FieldRole, self.vwallSpin)
        self.frecycleSpin = QtGui.QDoubleSpinBox(self.formLayoutWidget_5)
        self.frecycleSpin.setMinimum(-10.0)
        self.frecycleSpin.setSingleStep(0.01)
        self.frecycleSpin.setProperty("value", 0.95)
        self.frecycleSpin.setObjectName("frecycleSpin")
        self.formLayout_6.setWidget(7, QtGui.QFormLayout.FieldRole, self.frecycleSpin)
        self.fredistributeSpin = QtGui.QDoubleSpinBox(self.formLayoutWidget_5)
        self.fredistributeSpin.setMinimum(-10.0)
        self.fredistributeSpin.setSingleStep(0.1)
        self.fredistributeSpin.setProperty("value", 0.9)
        self.fredistributeSpin.setObjectName("fredistributeSpin")
        self.formLayout_6.setWidget(8, QtGui.QFormLayout.FieldRole, self.fredistributeSpin)
        self.dneutSpin = QtGui.QDoubleSpinBox(self.formLayoutWidget_5)
        self.dneutSpin.setMinimum(-10.0)
        self.dneutSpin.setSingleStep(0.1)
        self.dneutSpin.setProperty("value", 0.0)
        self.dneutSpin.setObjectName("dneutSpin")
        self.formLayout_6.setWidget(11, QtGui.QFormLayout.FieldRole, self.dneutSpin)
        self.fimpSpin = QtGui.QDoubleSpinBox(self.formLayoutWidget_5)
        self.fimpSpin.setMinimum(-10.0)
        self.fimpSpin.setSingleStep(0.1)
        self.fimpSpin.setProperty("value", 0.0)
        self.fimpSpin.setObjectName("fimpSpin")
        self.formLayout_6.setWidget(13, QtGui.QFormLayout.FieldRole, self.fimpSpin)
        self.sheath_gammaSpin = QtGui.QDoubleSpinBox(self.formLayoutWidget_5)
        self.sheath_gammaSpin.setMinimum(-10.0)
        self.sheath_gammaSpin.setSingleStep(0.1)
        self.sheath_gammaSpin.setProperty("value", 6.5)
        self.sheath_gammaSpin.setObjectName("sheath_gammaSpin")
        self.formLayout_6.setWidget(15, QtGui.QFormLayout.FieldRole, self.sheath_gammaSpin)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.NnormLine = QtGui.QLineEdit(self.formLayoutWidget_5)
        self.NnormLine.setObjectName("NnormLine")
        self.horizontalLayout_5.addWidget(self.NnormLine)
        self.formLayout_6.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.nlossLine = QtGui.QLineEdit(self.formLayoutWidget_5)
        self.nlossLine.setObjectName("nlossLine")
        self.formLayout_6.setWidget(12, QtGui.QFormLayout.FieldRole, self.nlossLine)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(620, 20, 221, 71))
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 70, 221, 71))
        self.groupBox_8.setObjectName("groupBox_8")
        self.formLayoutWidget_6 = QtGui.QWidget(self.groupBox_7)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(8, 13, 201, 71))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_10 = QtGui.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_10.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_10.setContentsMargins(0, 0, 0, 0)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_49 = QtGui.QLabel(self.formLayoutWidget_6)
        self.label_49.setObjectName("label_49")
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_49)
        self.scaleDoubleSpin = QtGui.QDoubleSpinBox(self.formLayoutWidget_6)
        self.scaleDoubleSpin.setObjectName("scaleDoubleSpin")
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.FieldRole, self.scaleDoubleSpin)
        self.label_62 = QtGui.QLabel(self.formLayoutWidget_6)
        self.label_62.setObjectName("label_62")
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_62)
        self.bndry_allLine = QtGui.QLineEdit(self.formLayoutWidget_6)
        self.bndry_allLine.setStatusTip("")
        self.bndry_allLine.setObjectName("bndry_allLine")
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.FieldRole, self.bndry_allLine)
        self.groupBox_9 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_9.setGeometry(QtCore.QRect(620, 140, 221, 121))
        self.groupBox_9.setObjectName("groupBox_9")
        self.formLayoutWidget_7 = QtGui.QWidget(self.groupBox_9)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(10, 12, 201, 108))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.formLayout_7 = QtGui.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_50 = QtGui.QLabel(self.formLayoutWidget_7)
        self.label_50.setObjectName("label_50")
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_50)
        self.scale2Spin = QtGui.QSpinBox(self.formLayoutWidget_7)
        self.scale2Spin.setObjectName("scale2Spin")
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.scale2Spin)
        self.label_51 = QtGui.QLabel(self.formLayoutWidget_7)
        self.label_51.setObjectName("label_51")
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_51)
        self.label_52 = QtGui.QLabel(self.formLayoutWidget_7)
        self.label_52.setObjectName("label_52")
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_52)
        self.label_53 = QtGui.QLabel(self.formLayoutWidget_7)
        self.label_53.setObjectName("label_53")
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_53)
        self.sourceNeLine = QtGui.QLineEdit(self.formLayoutWidget_7)
        self.sourceNeLine.setStatusTip("")
        self.sourceNeLine.setObjectName("sourceNeLine")
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.FieldRole, self.sourceNeLine)
        self.functionDoubleSpin2 = QtGui.QDoubleSpinBox(self.formLayoutWidget_7)
        self.functionDoubleSpin2.setStatusTip("")
        self.functionDoubleSpin2.setObjectName("functionDoubleSpin2")
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.functionDoubleSpin2)
        self.fluxLine = QtGui.QLineEdit(self.formLayoutWidget_7)
        self.fluxLine.setStatusTip("")
        self.fluxLine.setObjectName("fluxLine")
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.FieldRole, self.fluxLine)
        self.groupBox_10 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_10.setGeometry(QtCore.QRect(620, 310, 221, 91))
        self.groupBox_10.setObjectName("groupBox_10")
        self.formLayoutWidget_8 = QtGui.QWidget(self.groupBox_10)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(10, 11, 201, 80))
        self.formLayoutWidget_8.setObjectName("formLayoutWidget_8")
        self.formLayout_8 = QtGui.QFormLayout(self.formLayoutWidget_8)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_54 = QtGui.QLabel(self.formLayoutWidget_8)
        self.label_54.setObjectName("label_54")
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_54)
        self.scale3Spin = QtGui.QSpinBox(self.formLayoutWidget_8)
        self.scale3Spin.setObjectName("scale3Spin")
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.scale3Spin)
        self.label_55 = QtGui.QLabel(self.formLayoutWidget_8)
        self.label_55.setObjectName("label_55")
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_55)
        self.label_56 = QtGui.QLabel(self.formLayoutWidget_8)
        self.label_56.setObjectName("label_56")
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_56)
        self.bndry_targetLine = QtGui.QLineEdit(self.formLayoutWidget_8)
        self.bndry_targetLine.setObjectName("bndry_targetLine")
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.FieldRole, self.bndry_targetLine)
        self.functionNViLine = QtGui.QLineEdit(self.formLayoutWidget_8)
        self.functionNViLine.setStatusTip("")
        self.functionNViLine.setObjectName("functionNViLine")
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.FieldRole, self.functionNViLine)
        self.groupBox_11 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_11.setGeometry(QtCore.QRect(620, 450, 221, 131))
        self.groupBox_11.setObjectName("groupBox_11")
        self.formLayoutWidget_9 = QtGui.QWidget(self.groupBox_11)
        self.formLayoutWidget_9.setGeometry(QtCore.QRect(9, 14, 200, 111))
        self.formLayoutWidget_9.setObjectName("formLayoutWidget_9")
        self.formLayout_9 = QtGui.QFormLayout(self.formLayoutWidget_9)
        self.formLayout_9.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_9.setContentsMargins(0, 0, 0, 0)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_58 = QtGui.QLabel(self.formLayoutWidget_9)
        self.label_58.setObjectName("label_58")
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_58)
        self.scale4Spin = QtGui.QSpinBox(self.formLayoutWidget_9)
        self.scale4Spin.setObjectName("scale4Spin")
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.FieldRole, self.scale4Spin)
        self.label_59 = QtGui.QLabel(self.formLayoutWidget_9)
        self.label_59.setObjectName("label_59")
        self.formLayout_9.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_59)
        self.functionDoubleSpin4 = QtGui.QDoubleSpinBox(self.formLayoutWidget_9)
        self.functionDoubleSpin4.setStatusTip("")
        self.functionDoubleSpin4.setObjectName("functionDoubleSpin4")
        self.formLayout_9.setWidget(2, QtGui.QFormLayout.FieldRole, self.functionDoubleSpin4)
        self.label_60 = QtGui.QLabel(self.formLayoutWidget_9)
        self.label_60.setObjectName("label_60")
        self.formLayout_9.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_60)
        self.label_61 = QtGui.QLabel(self.formLayoutWidget_9)
        self.label_61.setObjectName("label_61")
        self.formLayout_9.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_61)
        self.sourceLine = QtGui.QLineEdit(self.formLayoutWidget_9)
        self.sourceLine.setStatusTip("")
        self.sourceLine.setObjectName("sourceLine")
        self.formLayout_9.setWidget(4, QtGui.QFormLayout.FieldRole, self.sourceLine)
        self.powerfluxLine = QtGui.QLineEdit(self.formLayoutWidget_9)
        self.powerfluxLine.setStatusTip("")
        self.powerfluxLine.setObjectName("powerfluxLine")
        self.formLayout_9.setWidget(3, QtGui.QFormLayout.FieldRole, self.powerfluxLine)
        self.groupBox_12 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_12.setGeometry(QtCore.QRect(910, 240, 221, 121))
        self.groupBox_12.setObjectName("groupBox_12")
        self.formLayoutWidget_15 = QtGui.QWidget(self.groupBox_12)
        self.formLayoutWidget_15.setGeometry(QtCore.QRect(10, 10, 201, 104))
        self.formLayoutWidget_15.setObjectName("formLayoutWidget_15")
        self.formLayout_15 = QtGui.QFormLayout(self.formLayoutWidget_15)
        self.formLayout_15.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_15.setContentsMargins(0, 0, 0, 0)
        self.formLayout_15.setObjectName("formLayout_15")
        self.evolvePnCombo = QtGui.QComboBox(self.formLayoutWidget_15)
        self.evolvePnCombo.setStatusTip("")
        self.evolvePnCombo.setObjectName("evolvePnCombo")
        self.evolvePnCombo.addItem("")
        self.evolvePnCombo.addItem("")
        self.formLayout_15.setWidget(0, QtGui.QFormLayout.FieldRole, self.evolvePnCombo)
        self.label_78 = QtGui.QLabel(self.formLayoutWidget_15)
        self.label_78.setObjectName("label_78")
        self.formLayout_15.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_78)
        self.label_79 = QtGui.QLabel(self.formLayoutWidget_15)
        self.label_79.setObjectName("label_79")
        self.formLayout_15.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_79)
        self.label_80 = QtGui.QLabel(self.formLayoutWidget_15)
        self.label_80.setObjectName("label_80")
        self.formLayout_15.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_80)
        self.funcitonPnLine = QtGui.QLineEdit(self.formLayoutWidget_15)
        self.funcitonPnLine.setObjectName("funcitonPnLine")
        self.formLayout_15.setWidget(3, QtGui.QFormLayout.FieldRole, self.funcitonPnLine)
        self.TstartDoubleSpin = QtGui.QDoubleSpinBox(self.formLayoutWidget_15)
        self.TstartDoubleSpin.setStatusTip("")
        self.TstartDoubleSpin.setObjectName("TstartDoubleSpin")
        self.formLayout_15.setWidget(1, QtGui.QFormLayout.FieldRole, self.TstartDoubleSpin)
        self.scaleDoubleSpin6 = QtGui.QDoubleSpinBox(self.formLayoutWidget_15)
        self.scaleDoubleSpin6.setObjectName("scaleDoubleSpin6")
        self.formLayout_15.setWidget(2, QtGui.QFormLayout.FieldRole, self.scaleDoubleSpin6)
        self.label_77 = QtGui.QLabel(self.formLayoutWidget_15)
        self.label_77.setObjectName("label_77")
        self.formLayout_15.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_77)
        self.groupBox_13 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_13.setGeometry(QtCore.QRect(910, 140, 221, 51))
        self.groupBox_13.setObjectName("groupBox_13")
        self.formLayoutWidget_14 = QtGui.QWidget(self.groupBox_13)
        self.formLayoutWidget_14.setGeometry(QtCore.QRect(9, 14, 201, 31))
        self.formLayoutWidget_14.setObjectName("formLayoutWidget_14")
        self.formLayout_14 = QtGui.QFormLayout(self.formLayoutWidget_14)
        self.formLayout_14.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_14.setContentsMargins(0, 0, 0, 0)
        self.formLayout_14.setObjectName("formLayout_14")
        self.evolveNVnCombo = QtGui.QComboBox(self.formLayoutWidget_14)
        self.evolveNVnCombo.setStatusTip("")
        self.evolveNVnCombo.setObjectName("evolveNVnCombo")
        self.evolveNVnCombo.addItem("")
        self.evolveNVnCombo.addItem("")
        self.formLayout_14.setWidget(1, QtGui.QFormLayout.FieldRole, self.evolveNVnCombo)
        self.label_75 = QtGui.QLabel(self.formLayoutWidget_14)
        self.label_75.setObjectName("label_75")
        self.formLayout_14.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_75)
        self.groupBox_14 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_14.setGeometry(QtCore.QRect(910, 20, 221, 71))
        self.groupBox_14.setObjectName("groupBox_14")
        self.formLayoutWidget_13 = QtGui.QWidget(self.groupBox_14)
        self.formLayoutWidget_13.setGeometry(QtCore.QRect(9, 14, 201, 50))
        self.formLayoutWidget_13.setObjectName("formLayoutWidget_13")
        self.formLayout_13 = QtGui.QFormLayout(self.formLayoutWidget_13)
        self.formLayout_13.setContentsMargins(0, 0, 0, 0)
        self.formLayout_13.setObjectName("formLayout_13")
        self.label_72 = QtGui.QLabel(self.formLayoutWidget_13)
        self.label_72.setObjectName("label_72")
        self.formLayout_13.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_72)
        self.label_73 = QtGui.QLabel(self.formLayoutWidget_13)
        self.label_73.setObjectName("label_73")
        self.formLayout_13.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_73)
        self.scale5Spin = QtGui.QSpinBox(self.formLayoutWidget_13)
        self.scale5Spin.setObjectName("scale5Spin")
        self.formLayout_13.setWidget(0, QtGui.QFormLayout.FieldRole, self.scale5Spin)
        self.functionNnLine = QtGui.QLineEdit(self.formLayoutWidget_13)
        self.functionNnLine.setStatusTip("")
        self.functionNnLine.setObjectName("functionNnLine")
        self.formLayout_13.setWidget(1, QtGui.QFormLayout.FieldRole, self.functionNnLine)
        self.groupBox_15 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_15.setGeometry(QtCore.QRect(1180, 24, 221, 101))
        self.groupBox_15.setObjectName("groupBox_15")
        self.formLayoutWidget_3 = QtGui.QWidget(self.groupBox_15)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 201, 77))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_24 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_24)
        self.label_25 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_25.setObjectName("label_25")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_25)
        self.label_26 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_26.setObjectName("label_26")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_26)
        self.firstLine = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.firstLine.setObjectName("firstLine")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.firstLine)
        self.secondLine = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.secondLine.setObjectName("secondLine")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.secondLine)
        self.upwindLine = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.upwindLine.setObjectName("upwindLine")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.upwindLine)
        self.groupBox_16 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_16.setGeometry(QtCore.QRect(1180, 140, 221, 51))
        self.groupBox_16.setObjectName("groupBox_16")
        self.formLayoutWidget_4 = QtGui.QWidget(self.groupBox_16)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(10, 15, 201, 31))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_5 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.mxstepSpin = QtGui.QSpinBox(self.formLayoutWidget_4)
        self.mxstepSpin.setMinimum(-10000000)
        self.mxstepSpin.setMaximum(100000000)
        self.mxstepSpin.setProperty("value", 100000)
        self.mxstepSpin.setObjectName("mxstepSpin")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.mxstepSpin)
        self.groupBox_18 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_18.setGeometry(QtCore.QRect(920, 390, 491, 251))
        self.groupBox_18.setObjectName("groupBox_18")
        self.plainTextEdit = QtGui.QPlainTextEdit(self.groupBox_18)
        self.plainTextEdit.setGeometry(QtCore.QRect(9, 14, 471, 231))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 221, 131))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget_2 = QtGui.QWidget(self.groupBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 14, 201, 119))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.labelNOUT = QtGui.QLabel(self.formLayoutWidget_2)
        self.labelNOUT.setObjectName("labelNOUT")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelNOUT)
        self.LabelTimeStep = QtGui.QLabel(self.formLayoutWidget_2)
        self.LabelTimeStep.setObjectName("LabelTimeStep")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.LabelTimeStep)
        self.TimeStepSpin = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.TimeStepSpin.setMaximum(10000000)
        self.TimeStepSpin.setProperty("value", 1000)
        self.TimeStepSpin.setObjectName("TimeStepSpin")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.TimeStepSpin)
        self.label_17 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_17)
        self.MzSpin = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.MzSpin.setProperty("value", 1)
        self.MzSpin.setObjectName("MzSpin")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.MzSpin)
        self.label_18 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_18)
        self.MXGSpin = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.MXGSpin.setObjectName("MXGSpin")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.MXGSpin)
        self.NoutSpin = QtGui.QSpinBox(self.formLayoutWidget_2)
        self.NoutSpin.setMaximum(1000000)
        self.NoutSpin.setSingleStep(1)
        self.NoutSpin.setProperty("value", 500)
        self.NoutSpin.setObjectName("NoutSpin")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.NoutSpin)
        self.runScanningSimulation = QtGui.QPushButton(self.tab_2)
        self.runScanningSimulation.setGeometry(QtCore.QRect(1250, 700, 161, 25))
        self.runScanningSimulation.setObjectName("runScanningSimulation")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.outputStream = QtGui.QTextBrowser(self.tab)
        self.outputStream.setGeometry(QtCore.QRect(10, 10, 1401, 661))
        self.outputStream.setObjectName("outputStream")
        self.stopSimulation = QtGui.QPushButton(self.tab)
        self.stopSimulation.setGeometry(QtCore.QRect(10, 680, 1401, 25))
        self.stopSimulation.setObjectName("stopSimulation")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.variableCombo = QtGui.QComboBox(self.tab_3)
        self.variableCombo.setGeometry(QtCore.QRect(180, 40, 81, 22))
        self.variableCombo.setObjectName("variableCombo")
        self.variableCombo.addItem("")
        self.variableCombo.addItem("")
        self.variableCombo.addItem("")
        self.variableCombo.addItem("")
        self.variableCombo.addItem("")
        self.variableCombo.addItem("")
        self.tspin = QtGui.QSpinBox(self.tab_3)
        self.tspin.setGeometry(QtCore.QRect(270, 40, 53, 22))
        self.tspin.setMinimum(-10000000)
        self.tspin.setMaximum(10000000)
        self.tspin.setProperty("value", 0)
        self.tspin.setObjectName("tspin")
        self.createGraph = QtGui.QPushButton(self.tab_3)
        self.createGraph.setGeometry(QtCore.QRect(700, 70, 101, 25))
        self.createGraph.setObjectName("createGraph")
        self.xspin = QtGui.QSpinBox(self.tab_3)
        self.xspin.setGeometry(QtCore.QRect(330, 40, 53, 22))
        self.xspin.setMinimum(-10000000)
        self.xspin.setMaximum(10000000)
        self.xspin.setObjectName("xspin")
        self.tall = QtGui.QCheckBox(self.tab_3)
        self.tall.setGeometry(QtCore.QRect(270, 70, 84, 20))
        self.tall.setObjectName("tall")
        self.label_16 = QtGui.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(20, 40, 151, 16))
        self.label_16.setObjectName("label_16")
        self.zspin = QtGui.QSpinBox(self.tab_3)
        self.zspin.setGeometry(QtCore.QRect(450, 40, 53, 22))
        self.zspin.setMinimum(-1000000)
        self.zspin.setMaximum(10000000)
        self.zspin.setObjectName("zspin")
        self.yspin = QtGui.QSpinBox(self.tab_3)
        self.yspin.setGeometry(QtCore.QRect(390, 40, 53, 22))
        self.yspin.setMinimum(-999900)
        self.yspin.setMaximum(100000000)
        self.yspin.setObjectName("yspin")
        self.xall = QtGui.QCheckBox(self.tab_3)
        self.xall.setGeometry(QtCore.QRect(330, 70, 84, 20))
        self.xall.setObjectName("xall")
        self.valueButton = QtGui.QPushButton(self.tab_3)
        self.valueButton.setGeometry(QtCore.QRect(400, 107, 101, 25))
        self.valueButton.setObjectName("valueButton")
        self.valueLine = QtGui.QLineEdit(self.tab_3)
        self.valueLine.setGeometry(QtCore.QRect(180, 107, 211, 21))
        self.valueLine.setText("")
        self.valueLine.setObjectName("valueLine")
        self.pushButton_7 = QtGui.QPushButton(self.tab_3)
        self.pushButton_7.setGeometry(QtCore.QRect(700, 40, 101, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        self.divideByButton = QtGui.QPushButton(self.tab_3)
        self.divideByButton.setGeometry(QtCore.QRect(400, 137, 101, 25))
        self.divideByButton.setObjectName("divideByButton")
        self.divideByLine = QtGui.QLineEdit(self.tab_3)
        self.divideByLine.setGeometry(QtCore.QRect(180, 137, 211, 21))
        self.divideByLine.setObjectName("divideByLine")
        self.answerLine = QtGui.QLineEdit(self.tab_3)
        self.answerLine.setGeometry(QtCore.QRect(180, 167, 211, 21))
        self.answerLine.setObjectName("answerLine")
        self.label_19 = QtGui.QLabel(self.tab_3)
        self.label_19.setGeometry(QtCore.QRect(20, 110, 151, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtGui.QLabel(self.tab_3)
        self.label_20.setGeometry(QtCore.QRect(20, 140, 151, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtGui.QLabel(self.tab_3)
        self.label_21.setGeometry(QtCore.QRect(20, 167, 151, 16))
        self.label_21.setObjectName("label_21")
        self.collectedLabel = QtGui.QLabel(self.tab_3)
        self.collectedLabel.setGeometry(QtCore.QRect(170, 8, 771, 16))
        self.collectedLabel.setObjectName("collectedLabel")
        self.label_22 = QtGui.QLabel(self.tab_3)
        self.label_22.setGeometry(QtCore.QRect(20, 8, 161, 16))
        self.label_22.setObjectName("label_22")
        self.saveDefaultButton = QtGui.QPushButton(self.tab_3)
        self.saveDefaultButton.setGeometry(QtCore.QRect(520, 70, 101, 25))
        self.saveDefaultButton.setObjectName("saveDefaultButton")
        self.defaultCombo = QtGui.QComboBox(self.tab_3)
        self.defaultCombo.setGeometry(QtCore.QRect(520, 40, 171, 22))
        self.defaultCombo.setObjectName("defaultCombo")
        self.defaultCombo.addItem("")
        self.yall = QtGui.QCheckBox(self.tab_3)
        self.yall.setGeometry(QtCore.QRect(390, 70, 84, 20))
        self.yall.setObjectName("yall")
        self.zall = QtGui.QCheckBox(self.tab_3)
        self.zall.setGeometry(QtCore.QRect(450, 70, 84, 20))
        self.zall.setObjectName("zall")
        self.textOutput = QtGui.QTextEdit(self.tab_3)
        self.textOutput.setGeometry(QtCore.QRect(22, 430, 661, 261))
        self.textOutput.setReadOnly(True)
        self.textOutput.setObjectName("textOutput")
        self.label_64 = QtGui.QLabel(self.tab_3)
        self.label_64.setGeometry(QtCore.QRect(20, 700, 64, 25))
        self.label_64.setObjectName("label_64")
        self.dataTable = QtGui.QTableWidget(self.tab_3)
        self.dataTable.setGeometry(QtCore.QRect(23, 210, 661, 221))
        self.dataTable.setAlternatingRowColors(True)
        self.dataTable.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.dataTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.dataTable.setShowGrid(False)
        self.dataTable.setGridStyle(QtCore.Qt.SolidLine)
        self.dataTable.setObjectName("dataTable")
        self.dataTable.setColumnCount(4)
        self.dataTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(3, item)
        self.dataTable.horizontalHeader().setStretchLastSection(True)
        self.dataTable.verticalHeader().setDefaultSectionSize(20)
        self.commandButton = QtGui.QPushButton(self.tab_3)
        self.commandButton.setGeometry(QtCore.QRect(610, 700, 75, 25))
        self.commandButton.setObjectName("commandButton")
        self.collectedLabel_2 = QtGui.QLabel(self.tab_3)
        self.collectedLabel_2.setGeometry(QtCore.QRect(520, 20, 771, 16))
        self.collectedLabel_2.setObjectName("collectedLabel_2")
        self.frame = QtGui.QFrame(self.tab_3)
        self.frame.setGeometry(QtCore.QRect(700, 104, 701, 621))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.commandInput = ConsoleWidget(self.tab_3)
        self.commandInput.setGeometry(QtCore.QRect(89, 702, 511, 21))
        self.commandInput.setObjectName("commandInput")
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1436, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCompare = QtGui.QAction(MainWindow)
        self.actionCompare.setObjectName("actionCompare")
        self.actionFileHistory = QtGui.QAction(MainWindow)
        self.actionFileHistory.setObjectName("actionFileHistory")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionFileHistory)
        self.menuFile.addAction(self.actionCompare)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Program Name", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Loads the selected file for simualtion after editing", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "File Path", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Date Created", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Date Modified", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Load), QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Write to file", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("MainWindow", "Run Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainWindow", "Load Restart File", None, QtGui.QApplication.UnicodeUTF8))
        self.fileLabel.setText(QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Open File =", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Mesh", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "nx", None, QtGui.QApplication.UnicodeUTF8))
        self.nxSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Number of radial points", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "ny", None, QtGui.QApplication.UnicodeUTF8))
        self.nySpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Resolution along field-line", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "length", None, QtGui.QApplication.UnicodeUTF8))
        self.lengthSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Length of the domain in meters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "dx", None, QtGui.QApplication.UnicodeUTF8))
        self.dxSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Radial grid spacing [m]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "dy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "ixseps1", None, QtGui.QApplication.UnicodeUTF8))
        self.ixseps1Spin.setToolTip(QtGui.QApplication.translate("MainWindow", "Branch-cut indices, specifying that the grid is in the SOL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "ixseps2", None, QtGui.QApplication.UnicodeUTF8))
        self.ixseps2Spin.setToolTip(QtGui.QApplication.translate("MainWindow", "Branch-cut indices, specifying that the grid is in the SOL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Rxy", None, QtGui.QApplication.UnicodeUTF8))
        self.rxySpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Make the field-aligned metric tensor an identity metric", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Bpxy", None, QtGui.QApplication.UnicodeUTF8))
        self.bpxySpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Make the field-aligned metric tensor an identity metric", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Btxy", None, QtGui.QApplication.UnicodeUTF8))
        self.btxySpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Make the field-aligned metric tensor an identity metric", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Bxy", None, QtGui.QApplication.UnicodeUTF8))
        self.bxySpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Make the field-aligned metric tensor an identity metric", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "hthe", None, QtGui.QApplication.UnicodeUTF8))
        self.htheSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Make the field-aligned metric tensor an identity metric", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "sinty", None, QtGui.QApplication.UnicodeUTF8))
        self.sintySpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Make the field-aligned metric tensor an identity metric", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "SOL1D", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "diagnose", None, QtGui.QApplication.UnicodeUTF8))
        self.diagnoseCombo.setToolTip(QtGui.QApplication.translate("MainWindow", "Output additional diagnostics", None, QtGui.QApplication.UnicodeUTF8))
        self.diagnoseCombo.setItemText(0, QtGui.QApplication.translate("MainWindow", "true", None, QtGui.QApplication.UnicodeUTF8))
        self.diagnoseCombo.setItemText(1, QtGui.QApplication.translate("MainWindow", "false", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Nnorm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Bnorm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Tnorm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "AA", None, QtGui.QApplication.UnicodeUTF8))
        self.TnormSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Reference temperature [eV]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Eionize", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "vwall", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "frecycle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "fredistribute", None, QtGui.QApplication.UnicodeUTF8))
        self.EionizeSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Energy lost per ionisation [eV]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "redist_weight", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("MainWindow", "gaspuff", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("MainWindow", "dneut", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "nloss", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "fimp", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("MainWindow", "sheath_gamma", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("MainWindow", "atomic", None, QtGui.QApplication.UnicodeUTF8))
        self.atomicCombo.setToolTip(QtGui.QApplication.translate("MainWindow", " Include atomic processes (CX/iz/rc)", None, QtGui.QApplication.UnicodeUTF8))
        self.atomicCombo.setItemText(0, QtGui.QApplication.translate("MainWindow", "true", None, QtGui.QApplication.UnicodeUTF8))
        self.atomicCombo.setItemText(1, QtGui.QApplication.translate("MainWindow", "false", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("MainWindow", "area", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("MainWindow", "hyper", None, QtGui.QApplication.UnicodeUTF8))
        self.gaspuffSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "In normalised units ", None, QtGui.QApplication.UnicodeUTF8))
        self.redist_weightLine.setToolTip(QtGui.QApplication.translate("MainWindow", "Weighting for redistribution", None, QtGui.QApplication.UnicodeUTF8))
        self.hyperSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Numerical diffusion parameter", None, QtGui.QApplication.UnicodeUTF8))
        self.BnormdoubleSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Reference magnetic field [T]", None, QtGui.QApplication.UnicodeUTF8))
        self.AAdoubleSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Ion atomic number", None, QtGui.QApplication.UnicodeUTF8))
        self.vwallSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Velocity of neutrals at the wall, as fraction of Franck-Condon energy", None, QtGui.QApplication.UnicodeUTF8))
        self.frecycleSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Recycling fraction", None, QtGui.QApplication.UnicodeUTF8))
        self.fredistributeSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Fraction of recycled", None, QtGui.QApplication.UnicodeUTF8))
        self.dneutSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Scale neutral gas diffusion rate", None, QtGui.QApplication.UnicodeUTF8))
        self.fimpSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Impurity fraction", None, QtGui.QApplication.UnicodeUTF8))
        self.sheath_gammaSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Sheath heat transmission", None, QtGui.QApplication.UnicodeUTF8))
        self.NnormLine.setToolTip(QtGui.QApplication.translate("MainWindow", "Reference density [m^-3]", None, QtGui.QApplication.UnicodeUTF8))
        self.nlossLine.setToolTip(QtGui.QApplication.translate("MainWindow", "Neutral gas loss rate [1/s]", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.label_49.setText(QtGui.QApplication.translate("MainWindow", "scale", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setText(QtGui.QApplication.translate("MainWindow", "bndry_all", None, QtGui.QApplication.UnicodeUTF8))
        self.bndry_allLine.setToolTip(QtGui.QApplication.translate("MainWindow", "Default boundary condition", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("MainWindow", "Ne", None, QtGui.QApplication.UnicodeUTF8))
        self.label_50.setText(QtGui.QApplication.translate("MainWindow", "scale", None, QtGui.QApplication.UnicodeUTF8))
        self.label_51.setText(QtGui.QApplication.translate("MainWindow", "function", None, QtGui.QApplication.UnicodeUTF8))
        self.label_52.setText(QtGui.QApplication.translate("MainWindow", "flux", None, QtGui.QApplication.UnicodeUTF8))
        self.label_53.setText(QtGui.QApplication.translate("MainWindow", "source", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceNeLine.setToolTip(QtGui.QApplication.translate("MainWindow", "Particle input source", None, QtGui.QApplication.UnicodeUTF8))
        self.functionDoubleSpin2.setToolTip(QtGui.QApplication.translate("MainWindow", "Initial conditions", None, QtGui.QApplication.UnicodeUTF8))
        self.fluxLine.setToolTip(QtGui.QApplication.translate("MainWindow", "Particles per m^2 per second input", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("MainWindow", "NVi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_54.setText(QtGui.QApplication.translate("MainWindow", "scale", None, QtGui.QApplication.UnicodeUTF8))
        self.label_55.setText(QtGui.QApplication.translate("MainWindow", "function", None, QtGui.QApplication.UnicodeUTF8))
        self.label_56.setText(QtGui.QApplication.translate("MainWindow", "bndry_target", None, QtGui.QApplication.UnicodeUTF8))
        self.functionNViLine.setToolTip(QtGui.QApplication.translate("MainWindow", "Linear from 0 to 0.03 in y", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_11.setTitle(QtGui.QApplication.translate("MainWindow", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.label_58.setText(QtGui.QApplication.translate("MainWindow", "scale", None, QtGui.QApplication.UnicodeUTF8))
        self.label_59.setText(QtGui.QApplication.translate("MainWindow", "function", None, QtGui.QApplication.UnicodeUTF8))
        self.functionDoubleSpin4.setToolTip(QtGui.QApplication.translate("MainWindow", "Initial constant pressure", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("MainWindow", "powerflux", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setText(QtGui.QApplication.translate("MainWindow", "source", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceLine.setToolTip(QtGui.QApplication.translate("MainWindow", "Input power as function of y", None, QtGui.QApplication.UnicodeUTF8))
        self.powerfluxLine.setToolTip(QtGui.QApplication.translate("MainWindow", "Input power flux in W/m^2", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_12.setTitle(QtGui.QApplication.translate("MainWindow", "Pn", None, QtGui.QApplication.UnicodeUTF8))
        self.evolvePnCombo.setToolTip(QtGui.QApplication.translate("MainWindow", "volve neutral pressure? Otherwise Tn = Te model", None, QtGui.QApplication.UnicodeUTF8))
        self.evolvePnCombo.setItemText(0, QtGui.QApplication.translate("MainWindow", "true", None, QtGui.QApplication.UnicodeUTF8))
        self.evolvePnCombo.setItemText(1, QtGui.QApplication.translate("MainWindow", "false", None, QtGui.QApplication.UnicodeUTF8))
        self.label_78.setText(QtGui.QApplication.translate("MainWindow", "Tstart", None, QtGui.QApplication.UnicodeUTF8))
        self.label_79.setText(QtGui.QApplication.translate("MainWindow", "scale", None, QtGui.QApplication.UnicodeUTF8))
        self.label_80.setText(QtGui.QApplication.translate("MainWindow", "function", None, QtGui.QApplication.UnicodeUTF8))
        self.TstartDoubleSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Starting temperature in eV ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_77.setText(QtGui.QApplication.translate("MainWindow", "evolve", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_13.setTitle(QtGui.QApplication.translate("MainWindow", "NVn", None, QtGui.QApplication.UnicodeUTF8))
        self.evolveNVnCombo.setToolTip(QtGui.QApplication.translate("MainWindow", "Evolve neutral momentum?", None, QtGui.QApplication.UnicodeUTF8))
        self.evolveNVnCombo.setItemText(0, QtGui.QApplication.translate("MainWindow", "true", None, QtGui.QApplication.UnicodeUTF8))
        self.evolveNVnCombo.setItemText(1, QtGui.QApplication.translate("MainWindow", "false", None, QtGui.QApplication.UnicodeUTF8))
        self.label_75.setText(QtGui.QApplication.translate("MainWindow", "evolve", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_14.setTitle(QtGui.QApplication.translate("MainWindow", "Nn", None, QtGui.QApplication.UnicodeUTF8))
        self.label_72.setText(QtGui.QApplication.translate("MainWindow", "scale", None, QtGui.QApplication.UnicodeUTF8))
        self.label_73.setText(QtGui.QApplication.translate("MainWindow", "function", None, QtGui.QApplication.UnicodeUTF8))
        self.functionNnLine.setToolTip(QtGui.QApplication.translate("MainWindow", "Initial flat, low density", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_15.setTitle(QtGui.QApplication.translate("MainWindow", "ddy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "first", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "second", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "upwind", None, QtGui.QApplication.UnicodeUTF8))
        self.firstLine.setToolTip(QtGui.QApplication.translate("MainWindow", "Choose either C2 or C4", None, QtGui.QApplication.UnicodeUTF8))
        self.secondLine.setToolTip(QtGui.QApplication.translate("MainWindow", "Choose either C2 or C4", None, QtGui.QApplication.UnicodeUTF8))
        self.upwindLine.setToolTip(QtGui.QApplication.translate("MainWindow", "Choice of C2, U1, U2, U4, W3", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_16.setTitle(QtGui.QApplication.translate("MainWindow", "Solver", None, QtGui.QApplication.UnicodeUTF8))
        self.mxstepSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Maximum number of internal steps per output", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_18.setTitle(QtGui.QApplication.translate("MainWindow", "Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Timing", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNOUT.setText(QtGui.QApplication.translate("MainWindow", "NOUT", None, QtGui.QApplication.UnicodeUTF8))
        self.LabelTimeStep.setText(QtGui.QApplication.translate("MainWindow", "TimeStep", None, QtGui.QApplication.UnicodeUTF8))
        self.TimeStepSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Time between outputs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "MZ", None, QtGui.QApplication.UnicodeUTF8))
        self.MzSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Number of points in z direction", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "MXG", None, QtGui.QApplication.UnicodeUTF8))
        self.MXGSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "No guard cells needed in X", None, QtGui.QApplication.UnicodeUTF8))
        self.NoutSpin.setToolTip(QtGui.QApplication.translate("MainWindow", "Number of output time-steps", None, QtGui.QApplication.UnicodeUTF8))
        self.runScanningSimulation.setToolTip(QtGui.QApplication.translate("MainWindow", "Runs a series of simulations given an increment, a starting variable and a final variable", None, QtGui.QApplication.UnicodeUTF8))
        self.runScanningSimulation.setText(QtGui.QApplication.translate("MainWindow", "Run Scanning Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Change Inputs", None, QtGui.QApplication.UnicodeUTF8))
        self.stopSimulation.setText(QtGui.QApplication.translate("MainWindow", "Stop Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Output Stream", None, QtGui.QApplication.UnicodeUTF8))
        self.variableCombo.setToolTip(QtGui.QApplication.translate("MainWindow", "Choose what variable to plot", None, QtGui.QApplication.UnicodeUTF8))
        self.variableCombo.setItemText(0, QtGui.QApplication.translate("MainWindow", "Ne", None, QtGui.QApplication.UnicodeUTF8))
        self.variableCombo.setItemText(1, QtGui.QApplication.translate("MainWindow", "NVi", None, QtGui.QApplication.UnicodeUTF8))
        self.variableCombo.setItemText(2, QtGui.QApplication.translate("MainWindow", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.variableCombo.setItemText(3, QtGui.QApplication.translate("MainWindow", "Nn", None, QtGui.QApplication.UnicodeUTF8))
        self.variableCombo.setItemText(4, QtGui.QApplication.translate("MainWindow", "NVn", None, QtGui.QApplication.UnicodeUTF8))
        self.variableCombo.setItemText(5, QtGui.QApplication.translate("MainWindow", "Pn", None, QtGui.QApplication.UnicodeUTF8))
        self.tspin.setToolTip(QtGui.QApplication.translate("MainWindow", "Time value", None, QtGui.QApplication.UnicodeUTF8))
        self.createGraph.setToolTip(QtGui.QApplication.translate("MainWindow", "Display the data selected as a graph", None, QtGui.QApplication.UnicodeUTF8))
        self.createGraph.setText(QtGui.QApplication.translate("MainWindow", "Create Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.xspin.setToolTip(QtGui.QApplication.translate("MainWindow", "x value", None, QtGui.QApplication.UnicodeUTF8))
        self.tall.setToolTip(QtGui.QApplication.translate("MainWindow", "Select all of time ", None, QtGui.QApplication.UnicodeUTF8))
        self.tall.setText(QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Inputs variable(t,x,y,z) :", None, QtGui.QApplication.UnicodeUTF8))
        self.zspin.setToolTip(QtGui.QApplication.translate("MainWindow", "z value", None, QtGui.QApplication.UnicodeUTF8))
        self.yspin.setToolTip(QtGui.QApplication.translate("MainWindow", "y value", None, QtGui.QApplication.UnicodeUTF8))
        self.xall.setToolTip(QtGui.QApplication.translate("MainWindow", "Select all of x ", None, QtGui.QApplication.UnicodeUTF8))
        self.xall.setText(QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.valueButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Finds the value of the point specified by the inputs ignoring \'all\' selections", None, QtGui.QApplication.UnicodeUTF8))
        self.valueButton.setText(QtGui.QApplication.translate("MainWindow", "Value at Point", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setToolTip(QtGui.QApplication.translate("MainWindow", "Only need to use collect if data other than current simulation has been loaded", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("MainWindow", "Collect Data", None, QtGui.QApplication.UnicodeUTF8))
        self.divideByButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Selects a second point to divide the first by", None, QtGui.QApplication.UnicodeUTF8))
        self.divideByButton.setText(QtGui.QApplication.translate("MainWindow", "Divide by", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Value of Point:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Value to Divide By:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Answer: ", None, QtGui.QApplication.UnicodeUTF8))
        self.collectedLabel.setText(QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setToolTip(QtGui.QApplication.translate("MainWindow", "The current source of data in use", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Data Collected From = ", None, QtGui.QApplication.UnicodeUTF8))
        self.saveDefaultButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Save current settings so they can be used again", None, QtGui.QApplication.UnicodeUTF8))
        self.saveDefaultButton.setText(QtGui.QApplication.translate("MainWindow", "Save Default", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultCombo.setToolTip(QtGui.QApplication.translate("MainWindow", "Select default settings", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultCombo.setItemText(0, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.yall.setToolTip(QtGui.QApplication.translate("MainWindow", "Select all of y", None, QtGui.QApplication.UnicodeUTF8))
        self.yall.setText(QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.zall.setToolTip(QtGui.QApplication.translate("MainWindow", "Select all of z", None, QtGui.QApplication.UnicodeUTF8))
        self.zall.setText(QtGui.QApplication.translate("MainWindow", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.textOutput.setToolTip(QtGui.QApplication.translate("MainWindow", "The printed output from commands", None, QtGui.QApplication.UnicodeUTF8))
        self.label_64.setText(QtGui.QApplication.translate("MainWindow", "Command:", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTable.setToolTip(QtGui.QApplication.translate("MainWindow", "Table showing the current variables and imported modules", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Trace", None, QtGui.QApplication.UnicodeUTF8))
        self.dataTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Comments", None, QtGui.QApplication.UnicodeUTF8))
        self.commandButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Run current command", None, QtGui.QApplication.UnicodeUTF8))
        self.commandButton.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.collectedLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Load a default input selection", None, QtGui.QApplication.UnicodeUTF8))
        self.commandInput.setToolTip(QtGui.QApplication.translate("MainWindow", "Enter commands as if into a python command line", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Graphing", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompare.setText(QtGui.QApplication.translate("MainWindow", "Compare", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompare.setToolTip(QtGui.QApplication.translate("MainWindow", "Compare Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCompare.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Alt+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileHistory.setText(QtGui.QApplication.translate("MainWindow", "File History", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFileHistory.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+H", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

from console_widget import ConsoleWidget
