# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resize.ui'
#
# Created: Thu Aug 13 12:44:13 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Resize(object):
    def setupUi(self, Resize):
        Resize.setObjectName("Resize")
        Resize.resize(279, 300)
        self.ok = QtGui.QPushButton(Resize)
        self.ok.setGeometry(QtCore.QRect(40, 267, 75, 25))
        self.ok.setObjectName("ok")
        self.cancel = QtGui.QPushButton(Resize)
        self.cancel.setGeometry(QtCore.QRect(116, 267, 75, 25))
        self.cancel.setObjectName("cancel")
        self.apply = QtGui.QPushButton(Resize)
        self.apply.setGeometry(QtCore.QRect(193, 267, 75, 25))
        self.apply.setObjectName("apply")
        self.groupBox = QtGui.QGroupBox(Resize)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 261, 251))
        self.groupBox.setObjectName("groupBox")
        self.labelWidthSpin = QtGui.QSpinBox(self.groupBox)
        self.labelWidthSpin.setGeometry(QtCore.QRect(150, 197, 101, 22))
        self.labelWidthSpin.setMaximum(10000)
        self.labelWidthSpin.setObjectName("labelWidthSpin")
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 130, 161, 16))
        self.label_8.setObjectName("label_8")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 21, 111, 16))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 108, 111, 16))
        self.label_6.setObjectName("label_6")
        self.leftSpin = QtGui.QSpinBox(self.groupBox)
        self.leftSpin.setGeometry(QtCore.QRect(150, 38, 101, 22))
        self.leftSpin.setMaximum(10000)
        self.leftSpin.setObjectName("leftSpin")
        self.inputxSpin = QtGui.QSpinBox(self.groupBox)
        self.inputxSpin.setGeometry(QtCore.QRect(150, 173, 101, 22))
        self.inputxSpin.setMaximum(10000)
        self.inputxSpin.setObjectName("inputxSpin")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 64, 131, 16))
        self.label_2.setObjectName("label_2")
        self.inputSepSpin = QtGui.QSpinBox(self.groupBox)
        self.inputSepSpin.setGeometry(QtCore.QRect(150, 220, 101, 22))
        self.inputSepSpin.setMaximum(10000)
        self.inputSepSpin.setObjectName("inputSepSpin")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 43, 111, 16))
        self.label.setObjectName("label")
        self.widthSpin = QtGui.QSpinBox(self.groupBox)
        self.widthSpin.setGeometry(QtCore.QRect(150, 105, 101, 22))
        self.widthSpin.setMaximum(10000)
        self.widthSpin.setObjectName("widthSpin")
        self.labelxSpin = QtGui.QSpinBox(self.groupBox)
        self.labelxSpin.setGeometry(QtCore.QRect(150, 151, 101, 22))
        self.labelxSpin.setMaximum(10000)
        self.labelxSpin.setObjectName("labelxSpin")
        self.vSpin = QtGui.QSpinBox(self.groupBox)
        self.vSpin.setGeometry(QtCore.QRect(150, 60, 101, 22))
        self.vSpin.setMaximum(10000)
        self.vSpin.setObjectName("vSpin")
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 152, 171, 16))
        self.label_5.setObjectName("label_5")
        self.maxSpin = QtGui.QSpinBox(self.groupBox)
        self.maxSpin.setGeometry(QtCore.QRect(150, 82, 101, 22))
        self.maxSpin.setMaximum(10000)
        self.maxSpin.setObjectName("maxSpin")
        self.topSpin = QtGui.QSpinBox(self.groupBox)
        self.topSpin.setGeometry(QtCore.QRect(150, 16, 101, 22))
        self.topSpin.setMaximum(10000)
        self.topSpin.setObjectName("topSpin")
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 222, 121, 16))
        self.label_10.setObjectName("label_10")
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 199, 121, 16))
        self.label_9.setObjectName("label_9")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 86, 101, 16))
        self.label_4.setObjectName("label_4")
        self.hSpin = QtGui.QSpinBox(self.groupBox)
        self.hSpin.setGeometry(QtCore.QRect(150, 128, 101, 22))
        self.hSpin.setMaximum(10000)
        self.hSpin.setObjectName("hSpin")
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 175, 121, 16))
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Resize)
        QtCore.QMetaObject.connectSlotsByName(Resize)

    def retranslateUi(self, Resize):
        Resize.setWindowTitle(QtGui.QApplication.translate("Resize", "Resize and Reposition", None, QtGui.QApplication.UnicodeUTF8))
        self.ok.setText(QtGui.QApplication.translate("Resize", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel.setText(QtGui.QApplication.translate("Resize", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.apply.setText(QtGui.QApplication.translate("Resize", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Resize", "Size and Position Options", None, QtGui.QApplication.UnicodeUTF8))
        self.labelWidthSpin.setToolTip(QtGui.QApplication.translate("Resize", "Change the width of the labels", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Resize", "Horizontal Seperation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Resize", "Top Border", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Resize", "Box Width", None, QtGui.QApplication.UnicodeUTF8))
        self.leftSpin.setToolTip(QtGui.QApplication.translate("Resize", "change the left side of the border bewteen the mainwindow and the first boxes", None, QtGui.QApplication.UnicodeUTF8))
        self.inputxSpin.setToolTip(QtGui.QApplication.translate("Resize", "Change where within the box along the x axis the input control is", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Resize", "Vertical Seperation", None, QtGui.QApplication.UnicodeUTF8))
        self.inputSepSpin.setToolTip(QtGui.QApplication.translate("Resize", "Change the gap between the input controls", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Resize", "Left Border", None, QtGui.QApplication.UnicodeUTF8))
        self.widthSpin.setToolTip(QtGui.QApplication.translate("Resize", "change the width of the boxes", None, QtGui.QApplication.UnicodeUTF8))
        self.labelxSpin.setToolTip(QtGui.QApplication.translate("Resize", "Change where along the x axis of the box the label is", None, QtGui.QApplication.UnicodeUTF8))
        self.vSpin.setToolTip(QtGui.QApplication.translate("Resize", "change the vertical seperation between the boxes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Resize", "Label x position", None, QtGui.QApplication.UnicodeUTF8))
        self.maxSpin.setToolTip(QtGui.QApplication.translate("Resize", "change the limit of the length of each column of boxes", None, QtGui.QApplication.UnicodeUTF8))
        self.topSpin.setToolTip(QtGui.QApplication.translate("Resize", "change the top side of the border bewteen the mainwindow and the first boxes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Resize", "Input Seperation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Resize", "Label Width", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Resize", "Max Length", None, QtGui.QApplication.UnicodeUTF8))
        self.hSpin.setToolTip(QtGui.QApplication.translate("Resize", "Chagne the horizontal seperation between the boxes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Resize", "Input x position", None, QtGui.QApplication.UnicodeUTF8))

